default:
  token: 'put your token here'
  interval: 60 # How many minutes to wait before sending another batch of messages (Default: 60)

  # This setting overrides the 'interval' value set above
  randomize_interval:
    enabled: false  # If set to true, your interval is randomized based on the values below (Default: false)
    minimum_interval: 60 # Minimum interval in minutes (Default: 60)
    maximum_interval: 70 # Maximum interval in minutes (Default: 70)

  wait_between_messages:
    enabled: false # If set to true, the script waits between channels. Set this to true if you're getting rate limited (Default: false)
    minimum_interval: 3 # Maximum interval in seconds (Default: 3)
    maximum_interval: 5 # Maximum interval in seconds (Default: 5)

  avoid_spam:
    enabled: false # If set to true, the script prevents double-posting (Default: false)
    # Set both minimum and maximum to the same number if you want to only post when that number is reached, and not randomize
    minimum_messages: 2 # Minimum amount of messages other people post before you repost yours. (Default: 2)
    maximum_messages: 2 # Maximum amount of messages other people post before you repost yours. (Default: 2)

  work_hours:
    enabled: false # Make the script work only between the hours set below (Default: false)
    start_time: 8 # Start hour (0-23, Default: 7)
    end_time: 22 # End hour (0-23, Default: 22) 

  multiple_messages: 
    enabled: true # If set to true, the script will choose random .txt message file from /messages/ (Default: false)
    mode: 0 # 0 - choose random message file | 1 - sorts the messages (message1.txt, message2.txt etc), sends them all into one channel (Default: 0)

  wait_before_start: 0 # How many minutes to wait before starting the script (Default: 0)
  debug_mode: true # If set to true, you will get a log in the console every time a message is sent (Default: false)
  channels: # Channels where to send the message
    - 'xxxxxxxxxxxxxxxxxxx'
    - 'xxxxxxxxxxxxxxxxxxx' # etc
